# Ollama Agent Configuration

# Available agents
agents:
  - name: "thinker"
    model: "gemma3:4b"  # Change to your preferred model
    temperature: 0.7
    system_prompt: "You are a thoughtful assistant who carefully considers problems and solutions."
  
  - name: "critic"
    model: "gemma3:4b"  # Can use different models for different agents
    temperature: 0.5
    system_prompt: "You are a constructive critic who evaluates solutions and provides specific, actionable feedback."

# Default agent for single-agent mode
default_agent: "thinker"

# Self-reflection prompts (used in order)
reflection_prompts:
  - "Look at your previous response carefully. Are there any errors or improvements you would make? Please provide a corrected or enhanced version."
  - "Review your solution one more time. Consider edge cases, efficiency, and clarity. What final improvements would you make?"

# Debate mode configuration
debate:
  creator: "thinker"
  judge: "critic"
  rounds: 2  # Number of feedback-revision cycles